version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "psychic-astrology"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-default"
s3_prefix = "psychic-astrology"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
